# Generated by Django 2.2.2 on 2019-06-14 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_expiration', models.IntegerField(verbose_name='count expiration')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('code', models.CharField(error_messages={'unique': 'A code already exists.'}, help_text='Required. Has to be unique', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='5 length is a must', regex='^[a-zA-Z1-9]{5}$')], verbose_name='code')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PercentDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_expiration', models.IntegerField(verbose_name='count expiration')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('code', models.CharField(error_messages={'unique': 'A code already exists.'}, help_text='Required. Has to be unique', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='5 length is a must', regex='^[a-zA-Z1-9]{5}$')], verbose_name='code')),
                ('percent', models.IntegerField(verbose_name='percent')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PercentDiscountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.PercentDiscount', verbose_name='creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmountDiscountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.AmountDiscount', verbose_name='creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
