# Generated by Django 2.2.2 on 2019-06-13 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='phone number')),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('operator_type', models.CharField(choices=[('act', 'accountancy')], help_text="User's type of operator.", max_length=3, verbose_name='operator type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('manager_name', models.CharField(blank=True, max_length=30, verbose_name='manager name')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='phone number')),
                ('identity', models.CharField(blank=True, error_messages={'unique': 'A school with that identity already exists.'}, help_text='Required. Has to be unique', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_identity', message='must be a 8 digits text', regex='^\\d{8}$')], verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('customermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.CustomerModel')),
                ('child_national_code', models.DateTimeField(max_length=10, verbose_name='child national code')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customermodel',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.CustomerModel')),
                ('national_code', models.DateTimeField(max_length=10, verbose_name='national code')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customermodel',),
        ),
    ]
